/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rplorcamento.sistema.cadastro;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rplorcamento.conexao.rplorcamentoConexao;

/**
 *
 * @author PCPROGRAMADOR
 */
public class rplorcamentoTelaCadEstoqueBaixa extends javax.swing.JFrame {

    /**
     * Creates new form rplorcamentoTelaCadBaixaEstoque
     */
    public rplorcamentoTelaCadEstoqueBaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_materiais = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jText_material = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jText_vlUnitario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jText_qtdOriginal = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jText_vlTotal = new javax.swing.JTextField();
        jButton_calcularVlTotalOriginal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_controleEstoque = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jText_observacao = new javax.swing.JTextArea();
        jLabel60 = new javax.swing.JLabel();
        jText_unidMedOriginal = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        jText_qtdConvertida = new javax.swing.JSpinner();
        jButton_calcularConvercao = new javax.swing.JButton();
        jCbx_unidMedConvertida = new javax.swing.JComboBox();
        jButton_baixaEstoque = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jText_vlUnitarioVenda = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_materiais_B = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jText_nomeMaterialEstocado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jText_localEstocado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jText_observacaoEstocado = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jText_prateleiraEstocado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jText_ordemPrateleiraEstocado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jCbx_tipoLocalEstocado = new javax.swing.JComboBox();
        jButton_salvarEstoque = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_estocado = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("IMPRIMIR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setVisible(false);
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Lista de materiais:");

        jList_materiais.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jList_materiais.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_materiais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_materiaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_materiais);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Material:");

        jText_material.setEditable(false);
        jText_material.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Valor unitário:");

        jText_vlUnitario.setEditable(false);
        jText_vlUnitario.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Quantidade (unidade original):");

        jText_qtdOriginal.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Valor total:");

        jText_vlTotal.setEditable(false);
        jText_vlTotal.setBackground(new java.awt.Color(255, 255, 204));
        jText_vlTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jText_vlTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton_calcularVlTotalOriginal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_calcularVlTotalOriginal.setText("CALCULAR");
        jButton_calcularVlTotalOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcularVlTotalOriginalActionPerformed(evt);
            }
        });

        jTable_controleEstoque.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable_controleEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MATERIAL", "VL. UNITARIO", "QNTD.", "VL. TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_controleEstoque);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Observações:");

        jText_observacao.setColumns(20);
        jText_observacao.setLineWrap(true);
        jText_observacao.setRows(5);
        jScrollPane3.setViewportView(jText_observacao);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setText("Unidade de medida:");

        jText_unidMedOriginal.setEditable(false);
        jText_unidMedOriginal.setBackground(new java.awt.Color(255, 255, 204));

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton15.setText("CONV.");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setText("Quantidade (unidade convertida):");

        jText_qtdConvertida.setEnabled(false);

        jButton_calcularConvercao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_calcularConvercao.setText("CALCULAR");
        jButton_calcularConvercao.setEnabled(false);

        jCbx_unidMedConvertida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KG", "GR", "TNL", "ARB", "KM", "MT", "CM", "MM", "PÇ", "PCT", "CX", "SC", "BLD", "LT", "ML", "KL", "%" }));
        jCbx_unidMedConvertida.setEnabled(false);

        jButton_baixaEstoque.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_baixaEstoque.setText("REALIZAR MOVIMENTAÇÃO DE ESTOQUE");
        jButton_baixaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_baixaEstoqueActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Valor unitário de venda:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_material)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jText_vlUnitario)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jText_qtdOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_calcularVlTotalOriginal))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jText_unidMedOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCbx_unidMedConvertida, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel61)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jText_qtdConvertida, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton_calcularConvercao, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel14)
                                        .addComponent(jText_vlUnitarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jText_vlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_baixaEstoque)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_vlUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_calcularVlTotalOriginal)
                                    .addComponent(jText_qtdOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText_vlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton_baixaEstoque))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jText_unidMedOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton15)
                                    .addComponent(jCbx_unidMedConvertida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jText_qtdConvertida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_calcularConvercao))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_vlUnitarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BAIXA / CADASTRO DE MATERIAL", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Lista de materiais:");

        jList_materiais_B.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jList_materiais_B.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_materiais_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_materiais_BMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList_materiais_B);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Material:");

        jText_nomeMaterialEstocado.setEditable(false);
        jText_nomeMaterialEstocado.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Local de estoque:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Observações:");

        jText_observacaoEstocado.setColumns(20);
        jText_observacaoEstocado.setLineWrap(true);
        jText_observacaoEstocado.setRows(5);
        jScrollPane6.setViewportView(jText_observacaoEstocado);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Prateleira de estoque:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Ordem de prateleira:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Tipo de local:");

        jCbx_tipoLocalEstocado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Árido", "Frio", "Úmido", "Quente", "Abafado", "Vácuo", "Atmosférico", "Normal", "Subterraneo", "Aéreo", "Outros" }));

        jButton_salvarEstoque.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_salvarEstoque.setText("CADASTRAR MATERIAL EM ESTOQUE");
        jButton_salvarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salvarEstoqueActionPerformed(evt);
            }
        });

        jTable_estocado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable_estocado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MATERIAL", "LOCAL", "PRATELEIRA", "ORDEM PRAT."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable_estocado);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_salvarEstoque, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbx_tipoLocalEstocado, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jText_prateleiraEstocado, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                .addComponent(jText_localEstocado, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jText_nomeMaterialEstocado, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jText_ordemPrateleiraEstocado)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_nomeMaterialEstocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_localEstocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_prateleiraEstocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_ordemPrateleiraEstocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbx_tipoLocalEstocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_salvarEstoque)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("POSIÇÃO DE ESTOQUE", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Fechar Tela");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editor");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Salvar");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setText("Atualizar");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setText("Excluir");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem5.setText("Listar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem6.setText("Imprimir");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem7.setText("Contato do desenvolvedor");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        AcessarCalculadoraDeUnidadeDeMedida();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        CarregaInfoEstoques();
        CarregaTabelaEstoque();
        CarregaTabelaEstoque_B();

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jList_materiaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_materiaisMouseClicked

        ExibirInfoMateriais();

// TODO add your handling code here:
    }//GEN-LAST:event_jList_materiaisMouseClicked

    private void jButton_calcularVlTotalOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcularVlTotalOriginalActionPerformed

        CalcularVlTotalOriginal();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton_calcularVlTotalOriginalActionPerformed

    private void jButton_baixaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_baixaEstoqueActionPerformed

        SalvarEstoque();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton_baixaEstoqueActionPerformed

    private void jList_materiais_BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_materiais_BMouseClicked

        ExibirInfoMateriais_B();

// TODO add your handling code here:
    }//GEN-LAST:event_jList_materiais_BMouseClicked

    private void jButton_salvarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salvarEstoqueActionPerformed

        SalvarEstoque_B();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton_salvarEstoqueActionPerformed

    public void SalvarEstoque() {

        try {

            Connection conn = rplorcamentoConexao.GeraConexao();

            String sql = "insert into bd_rplorcamento.historicodeestoque values(?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement comando = conn.prepareStatement(sql);

            comando.setInt(1, CODIGO_ESTOQUE);
            comando.setString(2, jText_material.getText());
            comando.setDouble(3, Double.parseDouble(jText_vlUnitario.getText().replace(",", ".")));
            comando.setDouble(4, Double.parseDouble(jText_qtdOriginal.getValue().toString().replace(",", ".")));
            comando.setString(5, jText_unidMedOriginal.getText());
            if (jCbx_unidMedConvertida.isEnabled()) {
                comando.setString(6, (String) jCbx_unidMedConvertida.getSelectedItem());
                comando.setDouble(7, Double.parseDouble(jText_qtdConvertida.getValue().toString().replace(",", ".")));
            } else {
                comando.setString(6, null);
                comando.setDouble(7, 0.0);
            }

            if ("".equals(jText_vlUnitarioVenda.getText())) {
                comando.setDouble(8, 0.0);

            } else {
                comando.setDouble(8, Double.parseDouble(jText_vlUnitarioVenda.getText().replace(",", ".")));
            }
            comando.setDouble(9, Double.parseDouble(jText_vlTotal.getText().replace(",", ".")));
            comando.setString(10, jText_observacao.getText());

            //Execulta o comando no banco
            comando.executeUpdate();

            //Fechar as conecções
            comando.close();
            conn.close();

            AtualizarMateriais();
            JOptionPane.showMessageDialog(null, "Movimentação de estoque realizada com sucesso!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void AtualizarMateriais() {

        try {

            Connection conn = rplorcamentoConexao.GeraConexao();

            String sql = "update bd_rplorcamento.materiais set "
                    + "  unid_medida = ?,"
                    + "  quantidade = ?,"
                    + "  vl_unitario = ?, "
                    + "  vl_total = ?, "
                    + "  vl_final = ?,"
                    + "  vl_venda = ? "
                    + "  where id = " + CODIGO_MATERIAL;
            PreparedStatement comando = conn.prepareStatement(sql);

            if (jCbx_unidMedConvertida.isEnabled()) {
                if ("".equals(jText_vlUnitarioVenda.getText())) {
                    comando.setString(1, (String) jCbx_unidMedConvertida.getSelectedItem());
                    comando.setDouble(2, Double.parseDouble(jText_qtdConvertida.getValue().toString().replace(",", ".")));
                    comando.setDouble(3, Double.parseDouble(jText_vlUnitario.getText().replace(",", ".")));
                    comando.setDouble(4, Double.parseDouble(jText_vlTotal.getText().replace(",", ".")));
                    comando.setDouble(5, VALOR_FINAL);
                    comando.setDouble(6, Double.parseDouble(jText_vlUnitarioVenda.getText().replace(",", ".")));
                } else if (!"".equals(jText_vlUnitarioVenda.getText())) {
                    comando.setString(1, (String) jCbx_unidMedConvertida.getSelectedItem());
                    comando.setDouble(2, Double.parseDouble(jText_qtdConvertida.getValue().toString().replace(",", ".")));
                    comando.setDouble(3, Double.parseDouble(jText_vlUnitarioVenda.getText().replace(",", ".")));
                    comando.setDouble(4, Double.parseDouble(jText_vlTotal.getText().replace(",", ".")));
                    comando.setDouble(5, VALOR_FINAL);
                    comando.setDouble(6, Double.parseDouble(jText_vlUnitarioVenda.getText().replace(",", ".")));
                }
            } else {
                if ("".equals(jText_vlUnitarioVenda.getText())) {
                    comando.setString(1, (String) jText_unidMedOriginal.getText());
                    comando.setDouble(2, Double.parseDouble(jText_qtdOriginal.getValue().toString().replace(",", ".")));
                    comando.setDouble(3, Double.parseDouble(jText_vlUnitario.getText().replace(",", ".")));
                    comando.setDouble(4, Double.parseDouble(jText_vlTotal.getText().replace(",", ".")));
                    comando.setDouble(5, VALOR_FINAL);
                    comando.setDouble(6, Double.parseDouble(jText_vlUnitarioVenda.getText().replace(",", ".")));
                } else if (!"".equals(jText_vlUnitarioVenda.getText())) {
                    comando.setString(1, (String) jText_unidMedOriginal.getText());
                    comando.setDouble(2, Double.parseDouble(jText_qtdOriginal.getValue().toString().replace(",", ".")));
                    comando.setDouble(3, Double.parseDouble(jText_vlUnitarioVenda.getText().replace(",", ".")));
                    comando.setDouble(4, Double.parseDouble(jText_vlTotal.getText().replace(",", ".")));
                    comando.setDouble(5, VALOR_FINAL);
                    comando.setDouble(6, Double.parseDouble(jText_vlUnitarioVenda.getText().replace(",", ".")));
                }
            }

            //Execulta o comando no banco
            comando.executeUpdate();

            //Fechar as conecções
            comando.close();
            conn.close();

            LimparCampos();
            CarregaInfoEstoques();
            JOptionPane.showMessageDialog(null, "Estoque atualizado com sucesso!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void SalvarEstoque_B() {

        try {

            Connection conn = rplorcamentoConexao.GeraConexao();

            String sql = "insert into bd_rplorcamento.guardaestoque values(?,?,?,?,?,?,?)";

            PreparedStatement comando = conn.prepareStatement(sql);

            comando.setInt(1, CODIGO_MATERIAL);
            comando.setString(2, jText_nomeMaterialEstocado.getText());
            comando.setString(3, jText_localEstocado.getText());
            comando.setString(4, jText_prateleiraEstocado.getText());
            comando.setString(5, jText_ordemPrateleiraEstocado.getText());
            comando.setString(6, (String) jCbx_tipoLocalEstocado.getSelectedItem());
            comando.setString(7, jText_observacaoEstocado.getText());

            //Execulta o comando no banco
            comando.executeUpdate();

            //Fechar as conecções
            comando.close();
            conn.close();

            LimparCampos();
            //AtualizarMateriais();
            CarregaInfoEstoques();
            CarregaTabelaEstoque_B();
            JOptionPane.showMessageDialog(null, "Material guardado em estoque!");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void LimparCampos() {
        CODIGO_MATERIAL = 0;
        jText_material.setText(null);
        jText_vlUnitario.setText(null);
        jText_qtdOriginal.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0), null, null, Double.valueOf(1)));
        jText_unidMedOriginal.setText(null);
        jCbx_unidMedConvertida.setSelectedItem(null);
        jText_qtdConvertida.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0), null, null, Double.valueOf(1)));
        jText_vlUnitarioVenda.setText(null);
        jText_vlTotal.setText(null);
        jText_observacao.setText(null);

        //ABA 2
        jText_nomeMaterialEstocado.setText(null);
        jText_localEstocado.setText(null);
        jText_prateleiraEstocado.setText(null);
        jText_ordemPrateleiraEstocado.setText(null);
        jCbx_tipoLocalEstocado.setSelectedItem(null);
        jText_observacaoEstocado.setText(null);

    }

    public void CalcularVlTotalOriginal() {

        String vl_unit_venda = jText_vlUnitarioVenda.getText();

        if (!"".equals(vl_unit_venda)) {

            Double quantidade = Double.parseDouble(jText_qtdOriginal.getValue().toString().replace(",", "."));
            Double vl_unitariovenda = Double.parseDouble(jText_vlUnitarioVenda.getText().replace(",", "."));
            Double vl_total = quantidade * vl_unitariovenda;
            String strg_vl_total = String.valueOf(vl_total);

            jText_vlTotal.setText(strg_vl_total.replace(".", ","));

            Double vl_final = (vl_total - VALOR_DESCONTO) + VALOR_IMPOSTO;

            VALOR_FINAL = vl_final;

        } else {

            Double quantidade = Double.parseDouble(jText_qtdOriginal.getValue().toString().replace(",", "."));
            Double vl_unitario = Double.parseDouble(jText_vlUnitario.getText().replace(",", "."));
            Double vl_total = quantidade * vl_unitario;
            String strg_vl_total = String.valueOf(vl_total);

            jText_vlTotal.setText(strg_vl_total.replace(".", ","));

            Double vl_final = (vl_total - VALOR_DESCONTO) + VALOR_IMPOSTO;

            VALOR_FINAL = vl_final;

        }

    }

    public void ExibirInfoMateriais() {

        String buscarNome = (String) jList_materiais.getSelectedValue();

        try {

            if (!buscarNome.equals("")) {

                Connection conn = rplorcamentoConexao.GeraConexao();

                String sql = "SELECT * FROM bd_rplorcamento.materiais WHERE descricao = ?";

                PreparedStatement comando = conn.prepareStatement(sql);

                comando.setString(1, buscarNome);

                ResultSet rs = comando.executeQuery();

                while (rs.next()) {

                    CODIGO_MATERIAL = Integer.parseInt(rs.getString("id"));
                    jText_material.setText(rs.getString("nome_abreviado"));
                    jText_vlUnitario.setText(rs.getString("vl_unitario").replace(".", ","));
                    jText_qtdOriginal.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(rs.getString("quantidade")), null, null, Double.valueOf(1)));
                    jText_unidMedOriginal.setText(rs.getString("unid_medida"));
                    jText_vlTotal.setText(rs.getString("vl_total").replace(".", ","));
                    VALOR_DESCONTO = Double.parseDouble(rs.getString("vl_desconto"));
                    VALOR_IMPOSTO = Double.parseDouble(rs.getString("vl_imposto"));
                    VALOR_FINAL = Double.parseDouble(rs.getString("vl_final"));

                }

            } else {
                JOptionPane.showMessageDialog(null, "Selecione um funcionário!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void ExibirInfoMateriais_B() {

        String buscarNome = (String) jList_materiais_B.getSelectedValue();

        try {

            if (!buscarNome.equals("")) {

                Connection conn = rplorcamentoConexao.GeraConexao();

                String sql = "SELECT * FROM bd_rplorcamento.materiais WHERE descricao = ?";

                PreparedStatement comando = conn.prepareStatement(sql);

                comando.setString(1, buscarNome);

                ResultSet rs = comando.executeQuery();

                while (rs.next()) {

                    CODIGO_MATERIAL2 = Integer.parseInt(rs.getString("id"));
                    jText_nomeMaterialEstocado.setText(rs.getString("nome_abreviado"));

                }

            } else {
                JOptionPane.showMessageDialog(null, "Selecione um funcionário!");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void CarregaInfoEstoques() {

        try {

            Connection conn = rplorcamentoConexao.GeraConexao();

            String sql = "SELECT * FROM bd_rplorcamento.materiais";

            PreparedStatement comando = conn.prepareStatement(sql);

            ResultSet rs = comando.executeQuery();
//          cbx_id_pes_usuario.removeAllItems();

            jList_materiais.removeAll();

            ArrayList<String> lista = new ArrayList<String>();

            while (rs.next()) {

                lista.add(rs.getString("descricao"));

            }

            Iterator it = lista.iterator();
            DefaultListModel model = new DefaultListModel();
            jList_materiais.setModel(model);
            while (it.hasNext()) {
                String itemLista = (String) it.next();
                model.addElement(itemLista);
            }

            Iterator it2 = lista.iterator();
            DefaultListModel model2 = new DefaultListModel();
            jList_materiais_B.setModel(model2);
            while (it2.hasNext()) {
                String itemLista2 = (String) it2.next();
                model2.addElement(itemLista2);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void AcessarCalculadoraDeUnidadeDeMedida() {
        try {

            jCbx_unidMedConvertida.setEnabled(true);
            jText_qtdConvertida.setEnabled(true);
            jButton_calcularConvercao.setEnabled(true);

            JOptionPane.showMessageDialog(null, "Acesso ao conversor de medida.");
            Runtime.getRuntime().exec("cmd.exe /C start http://conversordemedidas.info/index.php?display=" + jText_qtdOriginal.getValue().toString());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Acesso Negado! Erro: " + ex.getMessage());

        }
    }

    public void CarregaTabelaEstoque() {

        try {

            Connection conn = rplorcamentoConexao.GeraConexao();

            String sql = "SELECT * FROM bd_rplorcamento.historicodeestoque";

            PreparedStatement comando = conn.prepareStatement(sql);

            ResultSet rs = comando.executeQuery();
//          cbx_id_pes_usuario.removeAllItems();

            DefaultTableModel modelo = (DefaultTableModel) jTable_controleEstoque.getModel();
            modelo.setNumRows(0);

            while (rs.next()) {

                modelo.addRow(
                        new Object[]{
                            rs.getString("material"),
                            rs.getString("vl_unitario").replace(".", ","),
                            "ORIG: " + rs.getString("quantidade_original").replace(".", ",") + " / CONV: " + rs.getString("quantidade_convertida").replace("0.00", "").replace(".", ","),
                            rs.getString("vl_total").replace(".", ",")
                        }
                );

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void CarregaTabelaEstoque_B() {

        try {

            Connection conn = rplorcamentoConexao.GeraConexao();

            String sql = "SELECT * FROM bd_rplorcamento.guardaestoque";

            PreparedStatement comando = conn.prepareStatement(sql);

            ResultSet rs = comando.executeQuery();
//          cbx_id_pes_usuario.removeAllItems();

            DefaultTableModel modelo = (DefaultTableModel) jTable_estocado.getModel();
            modelo.setNumRows(0);

            while (rs.next()) {

                modelo.addRow(
                        new Object[]{
                            rs.getString("material"),
                            rs.getString("local"),
                            rs.getString("prateleira"),
                            rs.getString("ordem")
                        }
                );

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rplorcamentoTelaCadEstoqueBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rplorcamentoTelaCadEstoqueBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rplorcamentoTelaCadEstoqueBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rplorcamentoTelaCadEstoqueBaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rplorcamentoTelaCadEstoqueBaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_baixaEstoque;
    private javax.swing.JButton jButton_calcularConvercao;
    private javax.swing.JButton jButton_calcularVlTotalOriginal;
    private javax.swing.JButton jButton_salvarEstoque;
    private javax.swing.JComboBox jCbx_tipoLocalEstocado;
    private javax.swing.JComboBox jCbx_unidMedConvertida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList_materiais;
    private javax.swing.JList jList_materiais_B;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_controleEstoque;
    private javax.swing.JTable jTable_estocado;
    private javax.swing.JTextField jText_localEstocado;
    private javax.swing.JTextField jText_material;
    private javax.swing.JTextField jText_nomeMaterialEstocado;
    private javax.swing.JTextArea jText_observacao;
    private javax.swing.JTextArea jText_observacaoEstocado;
    private javax.swing.JTextField jText_ordemPrateleiraEstocado;
    private javax.swing.JTextField jText_prateleiraEstocado;
    private javax.swing.JSpinner jText_qtdConvertida;
    private javax.swing.JSpinner jText_qtdOriginal;
    private javax.swing.JTextField jText_unidMedOriginal;
    private javax.swing.JTextField jText_vlTotal;
    private javax.swing.JTextField jText_vlUnitario;
    private javax.swing.JTextField jText_vlUnitarioVenda;
    // End of variables declaration//GEN-END:variables

    int CODIGO_MATERIAL;
    int CODIGO_MATERIAL2;
    int CODIGO_ESTOQUE;
    double VALOR_DESCONTO;
    double VALOR_IMPOSTO;
    double VALOR_FINAL;

}
